### ISSUE TITLE
Error downloading Images

### ISSUE THREAD

**Issue by futureweb** [idrm/create-panono-backup#4]
Hey there,

in the middle of the Backup the Script suddenly crashed with NullPointerException :-/

```
Downloading panorama [UNTITLED] (66zLEfl2zIjY) (64 / 378)...
Exception in thread "main" java.lang.NullPointerException
        at com.radiatic.createpanonobackup.Application.run(Application.java:322)
        at com.radiatic.createpanonobackup.Application.main(Application.java:59)

Q:\PanonoBackups>java -jar create-panono-backup-1.2.jar --username "xxx" --password "xxx" --includeUpf yes --timestampedFolders yes
Fetching panoramas with offset [-]
...
Fetching panoramas with offset [NPUgadnF3QIg]
Found 315 non-synced panoramas out of 378 total
Downloading panorama [UNTITLED] (66zLEfl2zIjY) (1 / 315)...
Exception in thread "main" java.lang.NullPointerException
        at com.radiatic.createpanonobackup.Application.run(Application.java:322)
        at com.radiatic.createpanonobackup.Application.main(Application.java:59)
```

I have a guess what's causing this ... 66zLEfl2zIjY is a manually uploaded Pano (EQUI download, Photoshop, EQUI upload) ... could it be that the missing UPF is causing the Problem?! ;-)

Andreas Schnederle-Wagner

**Comment by idrm** [comment]
Thanks for catching that! I updated the app to 1.2.1 to deal with missing UPFs.

**Comment by futureweb** [comment]
working - thx 4 fast fix! ;-)
